language: go
dist: bionic
notifications:
  email: true
go:
  - 1.13.x
addons:
  apt:
    packages:
      - libseccomp-dev
      - parallel
      - uidmap
      - pigz
before_install:
  - pushd /
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -u github.com/go-bindata/go-bindata/go-bindata
  - popd
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Run e2e Tests
      script:
        - make install
        - ./contrib/e2e-dockerfiles-build-test.sh
      env:
        - STATE_DIR=$HOME/img
    - stage: Build Release
      script:
        - make release
      before_deploy:
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/img-linux-amd64
          - cross/img-linux-amd64.md5
          - cross/img-linux-amd64.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "R50zL2rvOh3qlSDvGisOu9A82hihirdy66SLv7bkl/fO7O8/aU0ahVBX5irX5CRVf8I/XJYblg8rvfEUMxOLKEYq2Uf1+5GvLUprbiJohsMbViynfVmRONaRZv6VvrCHgu0LOGXk3T8h813juCZzgV0sRNrB8nAYdIv5At7sdo/Gy06AoB5LPF+lXJAmbLYnozHaNyXKwPvNprmbGMbpOdDoPpusZOuatpDBkVagw3ackJ6z3vAbOVRZzLLldbVXHLGuLsWsurqkRfF+U3pyd7oMJhOq0vFMY6ZBSdvzrS2ed7r/8KleQoBLLsz1ibJ/YxiHojS+qXg8L79ehzv8c64r8egffBt4owIDqSiCdU93PUa1r/7So07+Ji20yHTcM0hgixKeX8FWAhgXBHkIOZx8uXaqBQdtF3yOOrWjSpdfw7JEFNm4P1mVfZWu9bkc5+VTxuszmGT8C0QVcXf2Zwz664oIsPMn6ES1Xa5Fs7Gm+PvZWfucWHJtsUS3B89kfZ+1pM5eGHwBitn9O86zemZVHrX57S7A0YGcGm9wTgAHR/y529z6S7eX/tTFh971xMGZ7gCpIfL6vXZ0D5wccTyqx8e7bHAstyKYyPhrmr0s16pA7CeWd+aiLpE+4xb48tVLRfS2ow37B0qYLtbKtV5gLwDEFU3vkuBIhc3oZxs="
